// Generated by CoffeeScript 1.2.1-pre
var getValue, list_sync;

getValue = function(object, prop) {
  if (!(object && object[prop])) return null;
  if (_.isFunction(object[prop])) {
    return object[prop]();
  } else {
    return object[prop];
  }
};

list_sync = function(method, model, options) {
  options.url = "http://127.0.0.1:8080/api" + getValue(model, 'url');
  return Backbone.sync(method, model, options);
};
