// Generated by CoffeeScript 1.2.1-pre
var Channel, ChannelItemView, ChannelList, ChannelListItemView, ChannelListView, HomeView, IdentifyView, Member, MemberView, Track, TrackList, TrackListView, member, member_sync, models, session, sp, templates, ui, views,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

sp = getSpotifyApi(1);

models = sp.require("sp://import/scripts/api/models");

views = sp.require("sp://import/scripts/api/views");

ui = sp.require("sp://import/scripts/ui");

session = models.session;

templates = {
  member_identify: '\
    <H1>hell0 <%= id %></H1>\
    <form class=".form-vertical">\
      <label>Name</label>\
      <input type="text" name="name"><br>\
      <label>Email</label>\
      <input type="text" name="email"><br>\
      <button class="btn btn-success identity-save">submit</button>\
    </form>',
  home: 'hello <%= name %>\
    <div class="row">\
      <div class="span2" id="channel-list">\
      </div>\
      <div class="span8" id="channel-container">\
      </div>\
    </div',
  channel_list_item: '<%= name %></a>',
  channel_item: '<h1>welcome to radio <%= name%></h1>\
    <table class="track-list table-bordered table-striped">\
\
    </table>\
    <div>\
      What do you think about this channel?<br>\
      <textarea></textarea>\
      <div class="chat-list">\
      </div>\
    </div>',
  track_list_item: '<tr><td><%= name %></td></tr>'
};

member_sync = function(method, model, options) {
  options.url = "http://127.0.0.1:8080/api" + model.url();
  if (method === "read") options.url = options.url + model.get("id");
  return Backbone.sync(method, model, options);
};

Member = (function(_super) {

  __extends(Member, _super);

  Member.name = 'Member';

  function Member() {
    return Member.__super__.constructor.apply(this, arguments);
  }

  Member.prototype.url = function() {
    var base;
    return base = "/member/";
  };

  Member.prototype.sync = member_sync;

  Member.prototype.initialize = function() {
    return this.set({
      id: session.anonymousUserID
    });
  };

  return Member;

})(Backbone.Model);

MemberView = (function(_super) {

  __extends(MemberView, _super);

  MemberView.name = 'MemberView';

  function MemberView() {
    return MemberView.__super__.constructor.apply(this, arguments);
  }

  MemberView.prototype.initialize = function() {
    return this.render();
  };

  MemberView.prototype.render = function() {
    var dict;
    dict = this.model.toJSON();
    return this.$el.html(this.template(dict));
  };

  return MemberView;

})(Backbone.View);

IdentifyView = (function(_super) {

  __extends(IdentifyView, _super);

  IdentifyView.name = 'IdentifyView';

  function IdentifyView() {
    return IdentifyView.__super__.constructor.apply(this, arguments);
  }

  IdentifyView.prototype.events = {
    "click .identity-save": "save"
  };

  IdentifyView.prototype.save = function(e) {
    e.preventDefault();
    return this.model.save({
      name: (this.$el.find("input[name=name]")).val(),
      email: (this.$el.find("input[name=email]")).val()
    });
  };

  IdentifyView.prototype.template = _.template(templates.member_identify);

  return IdentifyView;

})(MemberView);

HomeView = (function(_super) {

  __extends(HomeView, _super);

  HomeView.name = 'HomeView';

  function HomeView() {
    return HomeView.__super__.constructor.apply(this, arguments);
  }

  HomeView.prototype.template = _.template(templates.home);

  return HomeView;

})(MemberView);

ChannelListItemView = (function(_super) {

  __extends(ChannelListItemView, _super);

  ChannelListItemView.name = 'ChannelListItemView';

  function ChannelListItemView() {
    return ChannelListItemView.__super__.constructor.apply(this, arguments);
  }

  ChannelListItemView.prototype.initialize = function() {
    return this.render();
  };

  ChannelListItemView.prototype.events = {
    "click": "selectModel"
  };

  ChannelListItemView.prototype.selectModel = function() {
    return this.model.set({
      selected: 1
    });
  };

  ChannelListItemView.prototype.template = _.template(templates.channel_list_item);

  ChannelListItemView.prototype.render = function() {
    this.$el.html(this.template(this.model.toJSON()));
    return this;
  };

  return ChannelListItemView;

})(Backbone.View);

ChannelListView = (function(_super) {

  __extends(ChannelListView, _super);

  ChannelListView.name = 'ChannelListView';

  function ChannelListView() {
    return ChannelListView.__super__.constructor.apply(this, arguments);
  }

  ChannelListView.prototype.initialize = function() {
    this.collection.on("add", this.render, this);
    this.collection.on("reset", this.renderList, this);
    this.collection.on("change:selected", this.showChannel, this);
    return this.collection.fetch();
  };

  ChannelListView.prototype.channelItemElement = false;

  ChannelListView.prototype.renderList = function(list) {
    this.$el.children().remove();
    return list.each(function(model) {
      return this.render(model);
    }, this);
  };

  ChannelListView.prototype.showChannel = function(model) {
    var channelItemView;
    channelItemView = new ChannelItemView({
      model: model,
      el: this.channelItemElement
    });
    channelItemView.render();
    return model.set({
      selected: 0
    }, {
      silent: true
    });
  };

  ChannelListView.prototype.render = function(model) {
    var channelItemView, element;
    channelItemView = new ChannelListItemView({
      model: model
    });
    element = channelItemView.render().el;
    return this.$el.append(element);
  };

  return ChannelListView;

})(Backbone.View);

Channel = (function(_super) {

  __extends(Channel, _super);

  Channel.name = 'Channel';

  function Channel() {
    return Channel.__super__.constructor.apply(this, arguments);
  }

  Channel.prototype.initialize = function() {
    return this.tracks = new TrackList();
  };

  Channel.prototype.url = function() {
    return "/channel/" + this.get("id") + "/listen";
  };

  Channel.prototype.tracks = false;

  Channel.prototype.listen = function() {
    var onSuccess;
    onSuccess = function() {
      var current, minutes, offset_ms, offset_sec, seconds, spotifyId, uri;
      this.tracks.reset(this.get("tracks"));
      current = this.get("current");
      spotifyId = current["current-id"];
      offset_ms = current["current-offset-ms"];
      offset_sec = Math.floor(offset_ms / 1000);
      minutes = Math.floor(offset_sec / 60);
      seconds = offset_sec % 60;
      uri = "spotify:track:" + spotifyId + "#" + minutes + ":" + seconds;
      console.log(uri);
      return models.player.play(uri);
    };
    onSuccess = _.bind(onSuccess, this);
    return this.fetch({
      success: onSuccess
    });
  };

  Channel.prototype.sync = list_sync;

  return Channel;

})(Backbone.Model);

ChannelItemView = (function(_super) {

  __extends(ChannelItemView, _super);

  ChannelItemView.name = 'ChannelItemView';

  function ChannelItemView() {
    return ChannelItemView.__super__.constructor.apply(this, arguments);
  }

  ChannelItemView.prototype.template = _.template(templates.channel_item);

  ChannelItemView.prototype.render = function() {
    var chatMessages, chatMessagesView, trackListView;
    this.$el.html(this.template(this.model.toJSON()));
    this.model.listen();
    trackListView = new TrackListView({
      collection: this.model.tracks,
      el: this.$el.find(".track-list")
    });
    chatMessages = new ChatMessages({
      channel: this.model
    });
    return chatMessagesView = new ChatMessagesView({
      collection: chatMessages,
      el: this.$el.find(".chat-list")
    });
  };

  return ChannelItemView;

})(Backbone.View);

ChannelList = (function(_super) {

  __extends(ChannelList, _super);

  ChannelList.name = 'ChannelList';

  function ChannelList() {
    return ChannelList.__super__.constructor.apply(this, arguments);
  }

  ChannelList.prototype.url = "/channels";

  ChannelList.prototype.model = Channel;

  ChannelList.prototype.sync = list_sync;

  return ChannelList;

})(Backbone.Collection);

Track = (function(_super) {

  __extends(Track, _super);

  Track.name = 'Track';

  function Track() {
    return Track.__super__.constructor.apply(this, arguments);
  }

  return Track;

})(Backbone.Model);

TrackListView = (function(_super) {

  __extends(TrackListView, _super);

  TrackListView.name = 'TrackListView';

  function TrackListView() {
    return TrackListView.__super__.constructor.apply(this, arguments);
  }

  TrackListView.prototype.initialize = function() {
    return this.collection.on("reset", this.render, this);
  };

  TrackListView.prototype.template = _.template(templates.track_list_item);

  TrackListView.prototype.render = function(tracks) {
    var iterator;
    this.$el.children().remove();
    iterator = _.bind(function(track) {
      var dict, spotifyId, spotifyTrack, uri;
      spotifyId = track.get("spotify-id");
      uri = "spotify:track:" + spotifyId;
      spotifyTrack = models.Track.fromURI(uri);
      dict = {
        name: spotifyTrack.name
      };
      return this.$el.append(this.template(dict));
    }, this);
    return tracks.each(iterator);
  };

  return TrackListView;

})(Backbone.View);

TrackList = (function(_super) {

  __extends(TrackList, _super);

  TrackList.name = 'TrackList';

  function TrackList() {
    return TrackList.__super__.constructor.apply(this, arguments);
  }

  TrackList.prototype.model = Track;

  return TrackList;

})(Backbone.Collection);

member = new Member();

member.fetch({
  error: function(object, response) {
    var identifyView;
    return identifyView = new IdentifyView({
      el: "#page-content",
      model: member
    });
  },
  success: function() {
    var channelList, channelListView, homeView;
    if (member.has("email")) {
      homeView = new HomeView({
        el: "#page-content",
        model: member
      });
      channelList = new ChannelList();
      channelListView = new ChannelListView({
        collection: channelList,
        el: "#channel-list"
      });
      return channelListView.channelItemElement = "#channel-container";
    } else {
      return console.error("cannot be here without email address");
    }
  }
});
